export const namedExports = {
  "./node_modules/react/index.js": [
    "cloneElement",
    "createElement",
    "PropTypes",
    "Children",
    "Component",
    "PureComponent",
    "useState",
    "useEffect",
    "useRef",
    "useLayoutEffect"
  ],
  "./node_modules/react-router-transition/node_modules/react/react.js": [
    "cloneElement",
    "createElement",
    "PropTypes",
    "Children",
    "Component"
  ],
  "./node_modules/react-dom/index.js": ["render"],
  "./node_modules/redux-logger/dist/redux-logger.js": ["createLogger"],
  "./node_modules/react-is/index.js": [
    "typeOf",
    "AsyncMode",
    "ConcurrentMode",
    "ContextConsumer",
    "ContextProvider",
    "Element",
    "ForwardRef",
    "Fragment",
    "Lazy",
    "Memo",
    "Portal",
    "Profiler",
    "StrictMode",
    "Suspense",
    "isValidElementType",
    "isAsyncMode",
    "isConcurrentMode",
    "isContextConsumer",
    "isContextProvider",
    "isElement",
    "isForwardRef",
    "isFragment",
    "isLazy",
    "isMemo",
    "isPortal",
    "isProfiler",
    "isStrictMode",
    "isSuspense"
  ]
};
